apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kafka
  name: kafka-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/matt/data/kafka
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kafka
  name: kafka-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka
    protocol: TCP
  - port: 9093
    targetPort: 9093
    name: controller
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: apache/kafka:latest
        ports:
          - containerPort: 9092
            name: kafka
          - containerPort: 9093
            name: controller
        env:
          - name: KAFKA_PROCESS_ROLES
            value: "broker,controller"
          - name: KAFKA_CONTROLLER_LISTENER_NAMES
            value: "CONTROLLER"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://:9092,CONTROLLER://:9093"
          - name: KAFKA_CONTROLLER_QUORUM_VOTERS
            value: "1@localhost:9093"
          - name: KAFKA_NODE_ID
            value: "1"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://localhost:9092"
          - name: KAFKA_LOG_DIRS
            value: "/var/lib/kafka/data"
        resources: {}
        volumeMounts:
        - name: kafka-pv
          mountPath: /var/lib/kafka/data
      nodeSelector:
        tier: backend
      hostname: kafka
      restartPolicy: Always
      volumes:
        - name: kafka-pv
          persistentVolumeClaim:
            claimName: kafka-pvc
