apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    gateway-access: "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: monitoring
  name: grafana-storage-pv
spec:
  storageClassName: grafana-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/matt/data/grafana/storage
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: grafana-storage-pvc
spec:
  storageClassName: grafana-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
