apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    gateway-access: "true"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-service
  namespace: kafka
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka
    protocol: TCP
  - port: 9093
    targetPort: 9093
    name: controller
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      volumes:
        - name: kafka-pv-storage
          hostPath:
            path: /home/matt/data/kafka
            type: DirectoryOrCreate
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: apache/kafka:latest
        ports:
          - containerPort: 9092
            name: kafka
          - containerPort: 9093
            name: controller
        env:
          - name: KAFKA_PROCESS_ROLES
            value: "broker,controller"
          - name: KAFKA_CONTROLLER_LISTENER_NAMES
            value: "CONTROLLER"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://:9092,CONTROLLER://:9093"
          - name: KAFKA_CONTROLLER_QUORUM_VOTERS
            value: "1@localhost:9093"
          - name: KAFKA_NODE_ID
            value: "1"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-0.kafka-service.kafka.svc.cluster.local:9092"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "PLAINTEXT"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_LOG_DIRS
            value: "/var/lib/kafka/data"
        resources: {}
        volumeMounts:
        - name: kafka-pv-storage
          mountPath: /var/lib/kafka/data
      # nodeSelector:
      #   tier: backend
      hostname: kafka
      restartPolicy: Always
